### ISSUE TITLE
链接失效了吗

### ISSUE THREAD

**Issue by RhLesbian** [huzpsb/BondageClubGod#2]
压缩包里的链接打不开了

**Comment by huzpsb** [comment]
哪个压缩包（吓）
link：
https://huzpsb.eu.org/bcg.pdf

**Comment by RhLesbian** [comment]
BCG的那个文本压缩包呀&nbsp;里面的链接打不开了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huzpsb/BondageClubGod"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月26日(星期天) 晚上10:00
***@***.***&gt;;
抄送:&nbsp;"半面红妆 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [huzpsb/BondageClubGod] 链接失效了吗 (Issue #2)





 
哪个压缩包（吓）
 link：
 https://huzpsb.eu.org/bcg.pdf

**Comment by huzpsb** [comment]
压缩包？ 什么压缩包？

**Comment by huzpsb** [comment]
是一个PDF和一个JS啊 哪来的压缩包（qwq）

**Comment by RhLesbian** [comment]
话说还是要像以前一样加你好友嘛0.0





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huzpsb/BondageClubGod"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月26日(星期天) 晚上10:02
***@***.***&gt;;
抄送:&nbsp;"半面红妆 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [huzpsb/BondageClubGod] 链接失效了吗 (Issue #2)





 
是一个PDF和一个JS啊 哪来的压缩包（qwq）

**Comment by huzpsb** [comment]
85%以上（数过）的功能不需要；咱也在3次更新前放开了awBOT的公众版。

**Comment by huzpsb** [comment]
[Closed] 已答复。如有需要，请重新开启本工单。
